java_library(
    name = 'base',
    srcs = glob(['src/**/*.java']),
    deps = [
        "//lib:commons-io",
        "//lib:commons-lang",
        "//lib:commons-codec",
        "//lib:commons-httpclient",
        "//lib:joda-time",
        "//lib:commons-logging",
        "//lib:log4j"
        ],
    visibility = ['PUBLIC']
)
