java_library(
    name = 'agent-bootstrapper',
    srcs = glob(['src/**/*.java']),
    deps = [
        "//agent-common:agent-common",
        "//lib:AppleJavaExtensions",
        "//base:base",
        "//lib:log4j",
        "//lib:commons-logging",
        "//lib:commons-io",

    ],
    visibility = ['PUBLIC']
)
